# Generated by Django 6.0.6 on 2026-06-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_adopciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adoptionlisting',
            new_name='gestion_ado_adoptio_b1db15_idx',
            old_name='gestion_adop_adoptio_7e2f02_idx',
        ),
        migrations.RenameIndex(
            model_name='adoptionlisting',
            new_name='gestion_ado_publish_a9452e_idx',
            old_name='gestion_adop_publish_55ac31_idx',
        ),
        migrations.RenameIndex(
            model_name='adoptionlisting',
            new_name='gestion_ado_created_0e0df4_idx',
            old_name='gestion_adop_created_b2d4c9_idx',
        ),
    ]
