# Generated by Django 6.0.6 on 2026-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_adopciones', '0003_adoptionlisting_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionlisting',
            name='imagenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
