# Generated by Django 6.0.6 on 2026-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_adopciones', '0004_adoptionlisting_imagenes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adoptionlisting',
            name='gestion_ado_adoptio_b1db15_idx',
        ),
        migrations.AddIndex(
            model_name='adoptionlisting',
            index=models.Index(fields=['region', 'comuna'], name='gestion_ado_region_2a3066_idx'),
        ),
        migrations.RemoveField(
            model_name='adoptionlisting',
            name='adoption_status',
        ),
        migrations.RemoveField(
            model_name='adoptionlisting',
            name='is_urgent',
        ),
    ]
