# Generated by Django 6.0.6 on 2026-06-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_guardado', models.CharField(max_length=255, unique=True)),
                ('ruta_relativa', models.CharField(max_length=500, unique=True)),
                ('tipo_mime', models.CharField(max_length=120)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('tamano_bytes', models.PositiveIntegerField()),
                ('huella_sha256', models.CharField(blank=True, max_length=64)),
                ('servicio_origen', models.CharField(blank=True, max_length=80)),
                ('tipo_entidad', models.CharField(max_length=80)),
                ('id_entidad', models.PositiveIntegerField()),
                ('categoria', models.CharField(default='general', max_length=40)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('usuario_cargador_id', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', '-creado_en'],
                'indexes': [models.Index(fields=['tipo_entidad', 'id_entidad', 'activo'], name='gestion_arc_tipo_en_a0a9bd_idx'), models.Index(fields=['servicio_origen', 'tipo_entidad'], name='gestion_arc_servici_828875_idx'), models.Index(fields=['usuario_cargador_id', 'creado_en'], name='gestion_arc_usuario_ae65c1_idx'), models.Index(fields=['categoria', 'orden'], name='gestion_arc_categor_bd2e18_idx')],
            },
        ),
    ]
