# Generated by Django 6.0.4 on 2026-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostPetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'region', 'comuna'], name='gestion_mas_status_f24cf5_idx'), models.Index(fields=['created_at'], name='gestion_mas_created_71e891_idx')],
            },
        ),
    ]
