# Generated by Django 6.0.4 on 2026-05-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
