# Generated by Django 6.0.4 on 2026-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0002_lostpetreport_latitude_lostpetreport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreport',
            name='image_data_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lostpetreport',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
    ]
