# Generated by Django 6.0.4 on 2026-05-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0003_lostpetreport_image_data_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreport',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
