# Generated by Django 6.0.6 on 2026-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mascotas', '0006_foundpetlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetlead',
            name='imagenes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='imagenes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
